### ISSUE TITLE
Save Settings button doesn't save window position

### ISSUE THREAD

**Issue by LazyJedi** [BosslandGmbH/BuddyWing#12]
1. move bot window
2. press [save settings] button
3. press [reload] button
4. bot window moves to the previous position

**Comment by aevitas** [comment]
Will be fixed in the next drop, currently only character and global settings are saved by the save settings button, which shouldn't be the case.

**Comment by CryoGenesisX** [comment]
Also doesnt save the status of the plugins which i want activated or deactivated.
For instance the plugin Openlockboxes!

**Comment by aevitas** [comment]
@CryoGenesisX That's weird. We're currently calling `CharacterSettings.Save()`, which does the following: 

```
        var enabled = PluginManager.GetEnabledPlugins();
        if (enabled.Count() != 0)
        {
            EnabledPlugins = new List<string>(enabled);
        }
```

Therefore, the state of plugins should be stored properly. Are you sure?

Other than that, the code to address this issue is in place. If the plugins really aren't stored properly, please open a separate issue for that and I'll look further into it.
